### ISSUE TITLE
Add discussions to this project

### ISSUE THREAD

**Issue by Roms1383** [Halen84/ScriptHookRDR2DotNet-V2#9]
Hi @Halen84, would you mind opening the [Discussions](https://docs.github.com/discussions) tab on your Github repository ?
This way we could discuss usage of the internals, or inquire about gameplay mechanics there instead of opening an `Issue` like I'm doing here.

For example, I'd like more informations about patrol routes: as far as I understand looking at the definitions, a patrol route can be created, added nodes and links, opened, closed an deleted. Something that I quite don't get though, is that I would expect `TASK::CREATE_PATROL_ROUTE` to return a handle, since a `patrolRoute` parameter is expected in the other methods. Any clue on how to work this out ?

**Comment by Halen84** [comment]
Sure. Should be added now.

As for `TASK::CREATE_PATROL_ROUTE`, it doesn't return anything most likely because the creation of nodes and links is handled in the engine for the script threads, so the native probably also handles the creation of it in the engine.

Looking at the decompiled scripts, it looks like you first have to follow these steps in order:
1) Open a patrol route with `TASK::OPEN_PATROL_ROUTE()`
2) Create your nodes with `TASK::ADD_PATROL_ROUTE_NODE()`
3) Link the created nodes with `TASK::ADD_PATROL_ROUTE_LINK()`
4) `TASK::CLOSE_PATROL_ROUTE()` when you have finished creating and linking nodes
5) `TASK::CREATE_PATROL_ROUTE()` when all of the above has been finished
6) `TASK::DELETE_PATROL_ROUTE()` when the patrol route is no longer needed. This will be needed so the engine can free up any allocated resources created by these natives.

Very similar process to task sequences for example.

**Comment by Roms1383** [comment]
Thanks a lot ! I'm completely new to RDR game engine, so in that sense I'm still unfamiliar with `task sequence` (but I've already tried a couple of `task` 2 days ago), so I'm probably gonna inquire some more in `Discussions` 😅.
